version: "1"

tasks:
  planner:
    prompt-string: |
      # Find an improvement or issue

      Look through the swarm/PLAN.md file and the code base in general and find something to improve. Don't add any brand new features - just try to round out the features that are already in place. E.g. if something could be improved, or it's missing something. We're trying to get to a shippable MVP, don't need anything new, everything just needs to work. Don't duplicate what's already in ./swarm/todo/

      # Write a feature file

      Then plan out the feature and write it to ./swarm/todo/{feature-name}.pending.md

      # Exit condition

      If you fail to find an improvement, or if you've successfully written a single feature - exit immediately.
    model: opus
  coder:
    prompt-string: |
      # Find unfinished tasks

      Use your agent id to find tasks that you left unfinished by looking for files named:
      ./swarm/todo/\*.{SWARM_TASK_ID}.processing.md

      If you found a task to continue, skip the "Find a task to complete" section and jump straight to "Execute the task".

      # Find a task to complete

      Look under the ./swarm/todo/ folder for a file suffixed with ".pending.md" - and claim it as a task by renaming it to ".{SWARM_TASK_ID}.processing.md".
      Make sure the file you choose doesn't have any dependencies that are not completed.
      Make sure your work won't conflict with other work that is already in progress.
      If no tasks are found - skip the "Execute the task" step and go to the "If nothing to do" step.

      # Implement the task

      Then read the file and execute the task to completion, adding tests and testing when you think you need to.
      When done, rename the file to ".completed.md" and add a note about what you did.
      If you can\'t complete the task, rename the file to ".pending.md" and add a note about what went wrong to the file.
      When you\'re done, `git add .`, `git commit -m "a suitable message` and `git push` your changes to the remote repository.

      # If nothing to do

      If there are no pending tasks found, your job is to test the feature and report any issues.
      Then write those issues as new pending tasks in the swarm/todo/{feature-name}/ folder.
      When you have done that exit immediately!
    depends_on: [planner]
    model: sonnet

  tester:
    prompt-string: |
      # Find completed tasks to test

      Look under the ./swarm/todo/ folder for files suffixed with ".completed.md" that don't have a corresponding ".tested.md" file.

      # Test the feature

      For each completed task:
      1. Read the task description and understand what was implemented
      2. Review the code changes (check recent git commits if needed)
      3. Run any existing tests: `npm test`
      4. Manually test the feature using playwright-cli:
         - Start playwright if not running: `playwright-cli start`
         - Create a page: `PAGE_ID=$(playwright-cli new-page)`
         - Test the feature interactively
         - Take screenshots of any issues: `playwright-cli -e "await page.screenshot({ path: '/tmp/issue-screenshot.png' })" --page $PAGE_ID`
         - Close the page when done: `playwright-cli close-page $PAGE_ID`
      5. Check for:
         - Does it work as described?
         - Are there any errors in the console?
         - Is the UI responsive?
         - Are there edge cases that break it?

      # Report results

      Create a file named "{feature-name}.tested.md" with:
      - ✅ What works correctly
      - ❌ Any bugs or issues found
      - 📝 Suggested improvements
      - 🖼️ Screenshot paths if any issues found

      If you find bugs, create new pending tasks in swarm/todo/ for fixes.

      # Exit condition

      After testing one completed feature, exit immediately.
    model: sonnet
    depends_on:
      - task: coder
        condition: success


pipelines:
  development:
    iterations: 10
    tasks: [planner, coder, tester]